package loganalyzer

import (
	"regexp"
)

var deathMsgContains = []*regexp.Regexp{
	regexp.MustCompile(`([a-zA-Z0-9_]+) ((was shot by Arrow)(.*))`),
	regexp.MustCompile(`([a-zA-Z0-9_]+) ((was shot by)(.*))`),
	regexp.MustCompile(`([a-zA-Z0-9_]+) ((was shot by)(.*))`),
	regexp.MustCompile(`([a-zA-Z0-9_]+) ((was pricked to death)(.*))`),
	regexp.MustCompile(`([a-zA-Z0-9_]+) ((walked into a cactus whilst trying to escape)(.*))`),
	regexp.MustCompile(`([a-zA-Z0-9_]+) ((drowned)(.*))`),
	regexp.MustCompile(`([a-zA-Z0-9_]+) ((drowned whilst trying to escape)(.*))`),
	regexp.MustCompile(`([a-zA-Z0-9_]+) ((experienced kinetic energy)(.*))`),
	regexp.MustCompile(`([a-zA-Z0-9_]+) ((experienced kinetic energy whilst trying to escape)(.*))`),
	regexp.MustCompile(`([a-zA-Z0-9_]+) ((blew up)(.*))`),
	regexp.MustCompile(`([a-zA-Z0-9_]+) ((was blown up by)(.*))`),
	regexp.MustCompile(`([a-zA-Z0-9_]+) ((was blown up by)(.*))`),
	regexp.MustCompile(`([a-zA-Z0-9_]+) ((was killed by \[Intentional Game Design])(.*))`),
	regexp.MustCompile(`([a-zA-Z0-9_]+) ((hit the ground too hard)(.*))`),
	regexp.MustCompile(`([a-zA-Z0-9_]+) ((hit the ground too hard whilst trying to escape)(.*))`),
	regexp.MustCompile(`([a-zA-Z0-9_]+) ((fell from a high place)(.*))`),
	regexp.MustCompile(`([a-zA-Z0-9_]+) ((fell off a ladder)(.*))`),
	regexp.MustCompile(`([a-zA-Z0-9_]+) ((fell off some vines)(.*))`),
	regexp.MustCompile(`([a-zA-Z0-9_]+) ((fell off some weeping vines)(.*))`),
	regexp.MustCompile(`([a-zA-Z0-9_]+) ((fell off some twisting vines)(.*))`),
	regexp.MustCompile(`([a-zA-Z0-9_]+) ((fell off scaffolding)(.*))`),
	regexp.MustCompile(`([a-zA-Z0-9_]+) ((fell while climbing)(.*))`),
	regexp.MustCompile(`([a-zA-Z0-9_]+) ((was squashed by a falling anvil)(.*))`),
	regexp.MustCompile(`([a-zA-Z0-9_]+) ((was squashed by a falling anvil whilst fighting)(.*))`),
	regexp.MustCompile(`([a-zA-Z0-9_]+) ((was squashed by a falling block)(.*))`),
	regexp.MustCompile(`([a-zA-Z0-9_]+) ((was squashed by a falling block whilst fighting)(.*))`),
	regexp.MustCompile(`([a-zA-Z0-9_]+) ((went up in flames)(.*))`),
	regexp.MustCompile(`([a-zA-Z0-9_]+) ((walked into fire whilst fighting)(.*))`),
	regexp.MustCompile(`([a-zA-Z0-9_]+) ((burned to death)(.*))`),
	regexp.MustCompile(`([a-zA-Z0-9_]+) ((was burnt to a crisp whilst fighting)(.*))`),
	regexp.MustCompile(`([a-zA-Z0-9_]+) ((went off with a bang)(.*))`),
	regexp.MustCompile(`([a-zA-Z0-9_]+) ((went off with a bang whilst fighting)(.*))`),
	regexp.MustCompile(`([a-zA-Z0-9_]+) ((went off with a bang due to a firework fired from)(.*))`),
	regexp.MustCompile(`([a-zA-Z0-9_]+) ((tried to swim in lava)(.*))`),
	regexp.MustCompile(`([a-zA-Z0-9_]+) ((tried to swim in lava to escape)(.*))`),
	regexp.MustCompile(`([a-zA-Z0-9_]+) ((was struck by lightning)(.*))`),
	regexp.MustCompile(`([a-zA-Z0-9_]+) ((was struck by lightning whilst fighting)(.*))`),
	regexp.MustCompile(`([a-zA-Z0-9_]+) ((discovered the floor was lava)(.*))`),
	regexp.MustCompile(`([a-zA-Z0-9_]+) ((walked into danger zone due to)(.*))`),
	regexp.MustCompile(`([a-zA-Z0-9_]+) ((was killed by magic)(.*))`),
	regexp.MustCompile(`([a-zA-Z0-9_]+) ((was killed by)(.*))`),
	regexp.MustCompile(`([a-zA-Z0-9_]+) ((was killed by)(.*))`),
	regexp.MustCompile(`([a-zA-Z0-9_]+) ((was killed by magic whilst trying to escape)(.*))`),
	regexp.MustCompile(`([a-zA-Z0-9_]+) ((was slain by)(.*))`),
	regexp.MustCompile(`([a-zA-Z0-9_]+) ((was slain by)(.*))`),
	regexp.MustCompile(`([a-zA-Z0-9_]+) ((was fireballed by)(.*))`),
	regexp.MustCompile(`([a-zA-Z0-9_]+) ((was fireballed by)(.*))`),
	regexp.MustCompile(`([a-zA-Z0-9_]+) ((was stung to death)(.*))`),
	regexp.MustCompile(`([a-zA-Z0-9_]+) ((was pummeled by)(.*))`),
	regexp.MustCompile(`([a-zA-Z0-9_]+) ((was pummeled by)(.*))`),
	regexp.MustCompile(`([a-zA-Z0-9_]+) ((starved to death)(.*))`),
	regexp.MustCompile(`([a-zA-Z0-9_]+) ((starved to death whilst fighting)(.*))`),
	regexp.MustCompile(`([a-zA-Z0-9_]+) ((suffocated in a wall)(.*))`),
	regexp.MustCompile(`([a-zA-Z0-9_]+) ((suffocated in a wall whilst fighting)(.*))`),
	regexp.MustCompile(`([a-zA-Z0-9_]+) ((was squished too much)(.*))`),
	regexp.MustCompile(`([a-zA-Z0-9_]+) ((was squashed by)(.*))`),
	regexp.MustCompile(`([a-zA-Z0-9_]+) ((was poked to death by a sweet berry bush)(.*))`),
	regexp.MustCompile(`([a-zA-Z0-9_]+) ((was poked to death by a sweet berry bush whilst trying to escape)(.*))`),
	regexp.MustCompile(`([a-zA-Z0-9_]+) ((was killed trying to hurt)(.*))`),
	regexp.MustCompile(`([a-zA-Z0-9_]+) ((was killed by)(.*))`),
	regexp.MustCompile(`([a-zA-Z0-9_]+) ((was impaled by Trident)(.*))`),
	regexp.MustCompile(`([a-zA-Z0-9_]+) ((was impaled by)(.*))`),
	regexp.MustCompile(`([a-zA-Z0-9_]+) ((was impaled by)(.*))`),
	regexp.MustCompile(`([a-zA-Z0-9_]+) ((fell out of the world)(.*))`),
	regexp.MustCompile(`([a-zA-Z0-9_]+) ((didn't want to live in the same world as)(.*))`),
	regexp.MustCompile(`([a-zA-Z0-9_]+) ((withered away)(.*))`),
	regexp.MustCompile(`([a-zA-Z0-9_]+) ((withered away whilst fighting)(.*))`),
	regexp.MustCompile(`([a-zA-Z0-9_]+) ((was killed by even more magic)(.*))`),
	regexp.MustCompile(`([a-zA-Z0-9_]+) ((was roasted in dragon breath)(.*))`),
	regexp.MustCompile(`([a-zA-Z0-9_]+) ((was roasted in dragon breath by)(.*))`),
	regexp.MustCompile(`([a-zA-Z0-9_]+) ((fell out of the water)(.*))`),
	regexp.MustCompile(`([a-zA-Z0-9_]+) ((was doomed to fall)(.*))`),
	regexp.MustCompile(`([a-zA-Z0-9_]+) ((was doomed to fall by)(.*))`),
	regexp.MustCompile(`([a-zA-Z0-9_]+) ((was doomed to fall by)(.*))`),
	regexp.MustCompile(`([a-zA-Z0-9_]+) ((fell too far and was finished by)(.*))`),
	regexp.MustCompile(`([a-zA-Z0-9_]+) ((fell too far and was finished by)(.*))`),
	regexp.MustCompile(`([a-zA-Z0-9_]+) ((was stung to death by)(.*))`),
	regexp.MustCompile(`([a-zA-Z0-9_]+) ((died)(.*))`),
	regexp.MustCompile(`([a-zA-Z0-9_]+) ((died because of)(.*))`),
}
